@startuml
package "ejercicio2"
{
    Class Empleado
    {
        + realizarTarea(): void
    }

    Class Desarrollador extends Empleado

    Class Disenyador extends Empleado

    Class Gerente extends Empleado
}
@enduml