@startuml
skinparam classAttributeIconSize 0

package "ecommerce"
{
    package "pasarela_pago"
    {
        Abstract Class MetodoPago
        {
            + {abstract} validarMetodo(): boolean
            + {abstract} procesarPago(importe: double): void
        }

        Class TarjetaCredito extends MetodoPago
        {
            - nro_tarjeta: String
            - tipo: String

            - validarNumero(): boolean
            - validarTipo(): boolean
        }

        Class PayPal extends MetodoPago
        {
            - cuenta: String
            - saldo: double

            - validarTransaccion(importe: double): boolean
        }

        Class Bizum extends MetodoPago
        {
            - pin: String
            - telefono: String

            - {static} generarPin(): String
            - validarTelefono(): boolean
            - validarPin(): boolean
        }
    }
    package "comercios"
    {
        Class Tienda
        {
            + {static} realizarPago(metodo: MetodoPago): void
            + {static} iniciarPago(): void
            + {static} anyadirTarjeta(): MetodoPago
            + {static} anyadirPaypal(): MetodoPago
            + {static} anyadirBizum(): MetodoPago
        }
    }

    Tienda *-- MetodoPago
}
@enduml