@startuml

package "org.example" {
    Class Cadena {
        - String nombre
        - ArrayList<Programa> listaPrograma

        + boolean buscarInvitado(String nombre)
        + void invitadoAntes(String nombre)
        - boolean presenteEnLista(Programa programa)
        + void anyadirPrograma(Programa programa)
        + void eliminarPrograma(Programa programa)
    }

    Class Programa {
        - String nombre
        - Cadena cadena
        - int temporadas
        - ArrayList<Empleado> listaEmpleados
        - ArrayList<Invitado> lsitaInvitados
        - Empleado director

        + void invitadosTemporada(int temporada)
        + int vecesInvitado(String nombre)
        + void rastrearInvitado(String nombre)
        + void mostrarEmpleadosListados()
        - Empleado seleccionarEmpleado()
        - void cambiarDirectorEmpleados()
        + void eliminarEmpleado()
        + void mostrarInvitadosListados()
        - Invitado seleccionarInvitado()
        + void eliminarInvitado()
        + void crearEmpleado()
        + void crearInvitado()
    }

    Class Empleado {
        - String nombre
        - String id
        - String cargo
        - Empleado director

        + String generarId(int numeroEmpleado)
    }

    Class Invitado {
        - String nombre
        - String profesion
        - LocalDate fecha_visita
        - int temporada

        - LocalDate solicitarFecha()
        - int diaMaximo(int mes, int any)
    }

    Cadena -- Programa
    Programa *--> Empleado
    Programa *--> Empleado
    Empleado o--> Empleado
    Programa *--> Invitado
}

@enduml